// docs/.vitepress/theme/components/ChatInterface.vue
<script setup lang="ts">
import { nextTick, onMounted, onUnmounted, ref, watch } from 'vue'
import {
  type WebSocketMessage,
  useChatMode,
  useContentItems,
  useFileUpload,
  useLightbox,
  useMessageRenderer,
  useWebSocket,
} from '../composables/chat'
import {
  ChatHeader,
  ChatInputArea,
  ChatMessageList,
  ImageLightbox,
} from './chat'

// --- Composables ---
const {
  isMarkdownMode,
  renderContent,
  toggleMarkdownMode,
} = useMessageRenderer()

const {
  isGroupMode,
  groupId,
  toggleMode: toggleChatMode,
  getModeParams,
} = useChatMode()

const {
  lightboxImageSrc,
  isLightboxVisible,
  isPrevButtonDisabled,
  isNextButtonDisabled,
  imageTransform,
  isDragging,
  imageRenderKey,
  openLightbox,
  closeLightbox,
  showPrevImage,
  showNextImage,
  handleWheel,
  handleMouseDown,
} = useLightbox()

const {
  fileInputRef,
  isDragOver,
  triggerFileUpload,
  processFile: processUploadedFile,
  handleFileSelect,
  handleDragOver,
  handleDragLeave,
  handleDrop,
  handlePaste,
} = useFileUpload()

const {
  items: messageContentItems,
  addItem,
  removeItem: removeContentItem,
  moveItem: moveContentItem,
  clearItems: clearContentItems,
} = useContentItems()

// --- State ---
const messages = ref<Array<{
  type: 'sent' | 'received' | 'system'
  text?: string
  html?: string
  sender?: { nickname: string; avatar: string }
  buttons?: Array<{ text: string; data: string; style?: number }>
}>>([])

const newMessage = ref('')
const messageContainer = ref<HTMLElement | null>(null)

// --- WebSocket ---
const {
  ws,
  connectionStatus,
  wsUrl,
  statusText,
  statusClass,
  connect: connectWebSocket,
  disconnect: disconnectWebSocket,
  sendMessage: sendWsMessage,
  cancelConnection,
} = useWebSocket(
  (data) => {
    // Handle incoming message
    if (data.content) {
      const mainContent = data.content.filter((c: any) => c.type !== 'buttons')
      const buttonContent = data.content.find((c: any) => c.type === 'buttons')
      const buttons = buttonContent ? buttonContent.data.flat() : []

      const renderedHtml = renderContent(mainContent)

      if ((renderedHtml && renderedHtml.trim() !== '') || buttons.length > 0) {
        messages.value.push({
          type: 'received',
          html: renderedHtml,
          buttons,
          sender: data.sender || { nickname: '服务器', avatar: 'https://s2.loli.net/2023/03/25/bareSdYcsmRPOyZ.png' },
        })
        scrollToBottom()
      }
    }
  },
  (errorText) => {
    messages.value.push({ type: 'system', text: errorText })
  }
)

// Watch connection status for system messages
watch(connectionStatus, (newStatus, oldStatus) => {
  if (newStatus === 'connected')
    messages.value.push({ type: 'system', text: `已连接到 ${wsUrl.value}` })
  else if (newStatus === 'disconnected' && oldStatus === 'connected')
    messages.value.push({ type: 'system', text: '与服务器的连接已断开' })
  else if (newStatus === 'error')
    messages.value.push({ type: 'system', text: '连接出现错误' })
})

// Watch for group mode changes
watch([isGroupMode, groupId], ([newIsGroupMode, newGroupId], [oldIsGroupMode]) => {
  if (newIsGroupMode !== oldIsGroupMode) {
    if (newIsGroupMode) {
      messages.value.push({
        type: 'system',
        text: `已切换到群聊模式 (群组ID: ${newGroupId})`,
      })
    }
    else {
      messages.value.push({
        type: 'system',
        text: '已切换到私聊模式',
      })
    }
  }
})

// --- Methods ---
function scrollToBottom() {
  nextTick(() => {
    if (messageContainer.value)
      messageContainer.value.scrollTop = messageContainer.value.scrollHeight
  })
}

async function processFile(file: File) {
  const item = await processUploadedFile(file)
  if (item)
    addItem(item)
}

function sendRichMessage() {
  const content: Array<{ type: string; data: string }> = []

  // Add text content
  if (newMessage.value.trim()) {
    content.push({
      type: isMarkdownMode.value ? 'markdown' : 'text',
      data: newMessage.value,
    })
  }

  // Add media content
  content.push(...messageContentItems.value.map(item => ({
    type: item.type as 'image' | 'audio' | 'video',
    data: item.data,
  })))

  if (content.length === 0)
    return
  if (connectionStatus.value !== 'connected' || !ws.value)
    return

  const { userType, groupId: currentGroupId } = getModeParams()

  const messageToSend: WebSocketMessage = {
    bot_id: 'web',
    bot_self_id: 'web-client-001',
    msg_id: `msg_${Date.now()}`,
    user_type: userType,
    group_id: currentGroupId,
    user_id: 'user_web_01',
    sender: { nickname: '我', avatar: 'https://s2.loli.net/2023/10/05/GHjJNWBP4nezgIU.png' },
    user_pm: 3,
    content,
  }

  sendWsMessage(messageToSend)

  // Render sent message
  const renderedHtml = renderContent(content as Array<{ type: 'text' | 'audio' | 'video' | 'image' | 'markdown'; data: string }>)
  messages.value.push({
    type: 'sent',
    html: renderedHtml,
    sender: messageToSend.sender,
    buttons: [],
  })

  // Clear input
  newMessage.value = ''
  clearContentItems()
  scrollToBottom()
}

function sendSimpleMessage(text: string) {
  if (connectionStatus.value !== 'connected' || !ws.value || !text.trim())
    return

  const { userType, groupId: currentGroupId } = getModeParams()

  const messageToSend: WebSocketMessage = {
    bot_id: 'web',
    bot_self_id: 'web-client-001',
    msg_id: `msg_${Date.now()}`,
    user_type: userType,
    group_id: currentGroupId,
    user_id: 'user_web_01',
    sender: { nickname: '我', avatar: 'https://s2.loli.net/2023/10/05/GHjJNWBP4nezgIU.png' },
    user_pm: 3,
    content: [{ type: 'text', data: text }],
  }

  sendWsMessage(messageToSend)

  messages.value.push({
    type: 'sent',
    text,
    sender: messageToSend.sender,
    buttons: [],
  })

  scrollToBottom()
}

function handleButtonClick(button: { text: string; data: string; style?: number }) {
  if (connectionStatus.value !== 'connected' || !ws.value) {
    console.warn('无法发送按钮回调：WebSocket未连接。')
    return
  }

  const messageToSend: WebSocketMessage = {
    bot_id: 'web',
    bot_self_id: 'web-client-001',
    msg_id: `msg_${Date.now()}`,
    user_type: 'direct',
    group_id: null,
    user_id: 'user_web_01',
    sender: { nickname: '我', avatar: 'https://s2.loli.net/2023/10/05/GHjJNWBP4nezgIU.png' },
    user_pm: 3,
    content: [{ type: 'text', data: button.data }],
  }

  sendWsMessage(messageToSend)
  // console.log('发送按钮点击事件:', messageToSend)
}

function handleImageClick(src: string) {
  // Collect all images from messages
  const allImages: string[] = []
  messages.value.forEach((msg) => {
    if (msg.html) {
      const div = document.createElement('div')
      div.innerHTML = msg.html
      const imgs = div.querySelectorAll('img.chat-image')
      imgs.forEach((img) => {
        const imgSrc = (img as HTMLImageElement).src
        if (!allImages.includes(imgSrc))
          allImages.push(imgSrc)
      })
    }
  })

  const index = allImages.findIndex(s => s === src)
  openLightbox(src, allImages, index >= 0 ? index : 0)
}

// Lifecycle
onMounted(() => {
  connectWebSocket()
})

onUnmounted(() => {
  disconnectWebSocket()
})
</script>

<template>
  <div class="chat-container">
    <ChatHeader
      v-model:ws-url="wsUrl"
      :connection-status="connectionStatus"
      :is-group-mode="isGroupMode"
      :group-id="groupId"
      @toggle-mode="toggleChatMode"
      @cancel-connection="cancelConnection"
    />

    <ChatMessageList
      ref="messageContainer"
      :messages="messages"
      @resend="sendSimpleMessage"
      @button-click="handleButtonClick"
      @image-click="handleImageClick"
    />

    <ChatInputArea
      v-model="newMessage"
      :connection-status="connectionStatus"
      :is-markdown-mode="isMarkdownMode"
      :content-items="messageContentItems"
      :is-drag-over="isDragOver"
      @send="sendRichMessage"
      @reconnect="connectWebSocket"
      @toggle-markdown="toggleMarkdownMode"
      @remove-content-item="removeContentItem"
      @move-content-item="moveContentItem"
      @trigger-file-upload="(type: 'image' | 'audio' | 'video') => triggerFileUpload(fileInputRef, type)"
      @file-select="handleFileSelect($event, processFile)"
      @drag-over="handleDragOver"
      @drag-leave="handleDragLeave"
      @drop="handleDrop($event, processFile)"
      @paste="handlePaste($event, processFile)"
    />

    <ImageLightbox
      :image-src="lightboxImageSrc"
      :is-visible="isLightboxVisible"
      :is-prev-disabled="isPrevButtonDisabled"
      :is-next-disabled="isNextButtonDisabled"
      :image-transform="imageTransform"
      :is-dragging="isDragging"
      :image-render-key="imageRenderKey"
      @close="closeLightbox"
      @prev="showPrevImage"
      @next="showNextImage"
      @wheel="handleWheel"
      @mousedown="handleMouseDown"
    />

    <!-- Hidden file input -->
    <input
      ref="fileInputRef"
      type="file"
      style="display: none"
      multiple
      @change="handleFileSelect($event, processFile)"
    >
  </div>
</template>

<style scoped>
.chat-container {
  display: flex;
  flex-direction: column;
  height: 100%;
  font-family: sans-serif;
  background-color: var(--vp-c-bg);
  color: var(--vp-c-text-1);
}
</style>

// components/chat/ChatInterface.tsx
'use client'

import { useState, useEffect, useCallback, useRef } from 'react'
import { ChatHeader } from './ChatHeader'
import { ChatInputArea } from './ChatInputArea'
import { ChatMessageList } from './ChatMessageList'
import { ImageLightbox } from './ImageLightbox'
import { NodeMessagePanel } from './NodeMessagePanel'
import { useWebSocket } from '@/hooks/useWebSocket'
import { useLightbox } from '@/hooks/useLightbox'
import { useFileUpload } from '@/hooks/useFileUpload'
import { useContentItems } from '@/hooks/useContentItems'
import { useChatMode } from '@/hooks/useChatMode'
import { useMessageRenderer } from '@/hooks/useMessageRenderer'
import type { ChatMessage, NodeContent } from './types'

export function ChatInterface() {
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [newMessage, setNewMessage] = useState('')
  const [isNodePanelVisible, setIsNodePanelVisible] = useState(false)
  const [currentNodeData, setCurrentNodeData] = useState<NodeContent[]>([])

  const { isMarkdownMode, renderContent, toggleMarkdownMode } = useMessageRenderer()
  const { isGroupMode, groupId, toggleMode: toggleChatMode, getModeParams } = useChatMode()
  const lightbox = useLightbox()
  const fileUpload = useFileUpload()
  const { items: contentItems, addItem, removeItem, moveItem, clearItems } = useContentItems()

  const onWsMessage = useCallback((data: any) => {
    if (data.content) {
      const nodeContent = data.content.find((c: any) => c.type === 'node')
      if (nodeContent && Array.isArray(nodeContent.data)) {
        const nodeData: NodeContent[] = nodeContent.data.map((msg: any) => ({
          id: msg.id || String(Date.now()),
          username: msg.username || msg.sender?.nickname || '用户',
          avatar: msg.avatar || msg.sender?.avatar || 'https://s2.loli.net/2023/03/25/bareSdYcsmRPOyZ.png',
          messages: Array.isArray(msg.messages) ? msg.messages : [{ type: msg.type || 'text', data: msg.data || '' }],
        }))
        setMessages(prev => [...prev, {
          type: 'node',
          nodeData,
          sender: data.sender || { nickname: '服务器', avatar: 'https://s2.loli.net/2023/03/25/bareSdYcsmRPOyZ.png' },
        }])
        return
      }

      const mainContent = data.content.filter((c: any) => c.type !== 'buttons')
      const buttonContent = data.content.find((c: any) => c.type === 'buttons')
      const buttons = buttonContent ? buttonContent.data.flat() : []
      const renderedHtml = renderContent(mainContent)

      if ((renderedHtml && renderedHtml.trim() !== '') || buttons.length > 0) {
        setMessages(prev => [...prev, {
          type: 'received',
          html: renderedHtml,
          buttons,
          sender: data.sender || { nickname: '服务器', avatar: 'https://s2.loli.net/2023/03/25/bareSdYcsmRPOyZ.png' },
        }])
      }
    }
  }, [renderContent])

  const onWsError = useCallback((errorText: string) => {
    setMessages(prev => [...prev, { type: 'system', text: errorText }])
  }, [])

  const { wsUrl, setWsUrl, connectionStatus, connect: connectWs, disconnect: disconnectWs, sendMessage: sendWsMessage, cancelConnection } = useWebSocket(onWsMessage, onWsError)

  useEffect(() => {
    if (connectionStatus === 'connected') {
      setMessages(prev => [...prev, { type: 'system', text: `已连接到 ${wsUrl}` }])
    }
  }, [connectionStatus, wsUrl])

  useEffect(() => {
    connectWs()
    return () => disconnectWs()
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const processFile = useCallback(async (file: File) => {
    const item = await fileUpload.processFile(file)
    if (item) addItem(item)
  }, [fileUpload, addItem])

  const sendRichMessage = useCallback(() => {
    const content: Array<{ type: string; data: string }> = []

    if (newMessage.trim()) {
      content.push({
        type: isMarkdownMode ? 'markdown' : 'text',
        data: newMessage,
      })
    }

    content.push(...contentItems.map(item => ({
      type: item.type,
      data: item.data,
    })))

    if (content.length === 0) return
    if (connectionStatus !== 'connected') return

    const { userType, groupId: currentGroupId } = getModeParams()

    const messageToSend = {
      bot_id: 'web',
      bot_self_id: 'web-client-001',
      msg_id: `msg_${Date.now()}`,
      user_type: userType,
      group_id: currentGroupId,
      user_id: 'user_web_01',
      sender: { nickname: '我', avatar: 'https://s2.loli.net/2023/10/05/GHjJNWBP4nezgIU.png' },
      user_pm: 3,
      content,
    }

    sendWsMessage(messageToSend)

    const renderedHtml = renderContent(content as any)
    setMessages(prev => [...prev, {
      type: 'sent',
      html: renderedHtml,
      sender: messageToSend.sender,
      buttons: [],
    }])

    setNewMessage('')
    clearItems()
  }, [newMessage, isMarkdownMode, contentItems, connectionStatus, getModeParams, sendWsMessage, renderContent, clearItems])

  const sendSimpleMessage = useCallback((text: string) => {
    if (connectionStatus !== 'connected' || !text.trim()) return
    const { userType, groupId: currentGroupId } = getModeParams()

    const hasHtmlTags = /<[^>]+>/.test(text)
    const content: Array<{ type: string; data: string }> = []

    if (hasHtmlTags) {
      const tempDiv = document.createElement('div')
      tempDiv.innerHTML = text
      const textDiv = tempDiv.cloneNode(true) as HTMLDivElement
      const images = textDiv.querySelectorAll('img')
      images.forEach(img => img.remove())
      const plainText = (textDiv.textContent || textDiv.innerText || '').trim()
      if (plainText) content.push({ type: 'text', data: plainText })

      const originalImages = tempDiv.querySelectorAll('img')
      originalImages.forEach((img) => {
        const src = img.getAttribute('src') || ''
        if (src) content.push({ type: 'image', data: src })
      })
    }
    else {
      content.push({ type: 'text', data: text.trim() })
    }

    if (content.length === 0) return

    const messageToSend = {
      bot_id: 'web',
      bot_self_id: 'web-client-001',
      msg_id: `msg_${Date.now()}`,
      user_type: userType,
      group_id: currentGroupId,
      user_id: 'user_web_01',
      sender: { nickname: '我', avatar: 'https://s2.loli.net/2023/10/05/GHjJNWBP4nezgIU.png' },
      user_pm: 3,
      content,
    }
    sendWsMessage(messageToSend)

    const renderedHtml = renderContent(content as any)
    setMessages(prev => [...prev, {
      type: 'sent',
      html: renderedHtml,
      sender: messageToSend.sender,
      buttons: [],
    }])
  }, [connectionStatus, getModeParams, sendWsMessage, renderContent])

  const handleButtonClick = useCallback((button: { text: string; data: string; style?: number }) => {
    if (connectionStatus !== 'connected') return
    const messageToSend = {
      bot_id: 'web',
      bot_self_id: 'web-client-001',
      msg_id: `msg_${Date.now()}`,
      user_type: 'direct',
      group_id: null,
      user_id: 'user_web_01',
      sender: { nickname: '我', avatar: 'https://s2.loli.net/2023/10/05/GHjJNWBP4nezgIU.png' },
      user_pm: 3,
      content: [{ type: 'text', data: button.data }],
    }
    sendWsMessage(messageToSend)
  }, [connectionStatus, sendWsMessage])

  const handleImageClick = useCallback((src: string) => {
    const allImages: string[] = []
    messages.forEach((msg) => {
      if (msg.html) {
        const div = document.createElement('div')
        div.innerHTML = msg.html
        const imgs = div.querySelectorAll('img.chat-image')
        imgs.forEach((img) => {
          const imgSrc = (img as HTMLImageElement).src
          if (!allImages.includes(imgSrc)) allImages.push(imgSrc)
        })
      }
    })
    const index = allImages.findIndex(s => s === src)
    lightbox.openLightbox(src, allImages, index >= 0 ? index : 0)
  }, [messages, lightbox])

  const handleNodeClick = useCallback((nodeData: NodeContent[]) => {
    setCurrentNodeData(nodeData)
    setIsNodePanelVisible(true)
  }, [])

  const handleCopyToInput = useCallback((payload: { text?: string; html?: string }) => {
    const contentToCopy = payload.text || payload.html || ''
    clearItems()

    if (contentToCopy.includes('<')) {
      const tempDiv = document.createElement('div')
      tempDiv.innerHTML = contentToCopy
      const textDiv = tempDiv.cloneNode(true) as HTMLDivElement
      const images = textDiv.querySelectorAll('img')
      images.forEach(img => img.remove())
      const plainText = (textDiv.textContent || textDiv.innerText || '').trim()
      setNewMessage(plainText)

      images.forEach((img, index) => {
        const src = img.getAttribute('src') || ''
        if (src) {
          let fileName = `image_${index + 1}.png`
          if (src.startsWith('data:')) {
            const match = src.match(/data:image\/([a-zA-Z]+);/)
            if (match) fileName = `image_${index + 1}.${match[1]}`
          }
          else {
            const urlParts = src.split('/')
            const lastPart = urlParts[urlParts.length - 1]
            if (lastPart && lastPart.includes('.')) fileName = lastPart
          }
          addItem({ type: 'image', data: src, fileName, preview: src })
        }
      })
    }
    else {
      setNewMessage(contentToCopy.trim())
    }
  }, [addItem, clearItems])

  return (
    <div className="fd-chat-container">
      <ChatHeader
        wsUrl={wsUrl}
        setWsUrl={setWsUrl}
        connectionStatus={connectionStatus}
        isGroupMode={isGroupMode}
        groupId={groupId}
        onToggleMode={toggleChatMode}
        onCancelConnection={cancelConnection}
      />

      <ChatMessageList
        messages={messages}
        onResend={sendSimpleMessage}
        onButtonClick={handleButtonClick}
        onImageClick={handleImageClick}
        onCopy={handleCopyToInput}
        onNodeClick={handleNodeClick}
      />

      <ChatInputArea
        value={newMessage}
        onChange={setNewMessage}
        connectionStatus={connectionStatus}
        isMarkdownMode={isMarkdownMode}
        contentItems={contentItems}
        isDragOver={fileUpload.isDragOver}
        fileInputRef={fileUpload.fileInputRef}
        onSend={sendRichMessage}
        onReconnect={connectWs}
        onToggleMarkdown={toggleMarkdownMode}
        onRemoveContentItem={removeItem}
        onMoveContentItem={moveItem}
        onTriggerFileUpload={type => fileUpload.triggerFileUpload(fileUpload.fileInputRef, type)}
        onFileSelect={e => fileUpload.handleFileSelect(e, processFile)}
        onDragOver={fileUpload.handleDragOver}
        onDragLeave={fileUpload.handleDragLeave}
        onDrop={e => fileUpload.handleDrop(e, processFile)}
        onPaste={e => fileUpload.handlePaste(e, processFile)}
      />

      <ImageLightbox
        imageSrc={lightbox.lightboxImageSrc}
        isVisible={lightbox.isLightboxVisible}
        isPrevDisabled={lightbox.isPrevButtonDisabled}
        isNextDisabled={lightbox.isNextButtonDisabled}
        imageTransform={lightbox.imageTransform}
        isDragging={lightbox.isDragging}
        imageRenderKey={lightbox.imageRenderKey}
        onClose={lightbox.closeLightbox}
        onPrev={lightbox.showPrevImage}
        onNext={lightbox.showNextImage}
        onWheel={lightbox.handleWheel}
        onMouseDown={lightbox.handleMouseDown}
      />

      <NodeMessagePanel
        visible={isNodePanelVisible}
        nodeData={currentNodeData}
        onClose={() => setIsNodePanelVisible(false)}
      />
    </div>
  )
}
