// components/chat/ChatMessageItem.tsx
'use client'

import { useEffect, useRef, useState } from 'react'
import type { ChatMessage, NodeContent } from './types'

interface ChatMessageItemProps {
  message: ChatMessage
  onResend: (text: string) => void
  onButtonClick: (button: { text: string; data: string; style?: number }) => void
  onImageClick: (src: string) => void
  onCopy: (payload: { text?: string; html?: string }) => void
  onNodeClick: (nodeData: NodeContent[]) => void
}

const avatarMap: Record<string, string> = {
  'Wuyi无疑': 'https://s2.loli.net/2023/10/05/GHjJNWBP4nezgIU.png',
  'GsCore': 'https://s2.loli.net/2023/03/25/bareSdYcsmRPOyZ.png',
}

function getNodePreview(nodeData: NodeContent[]): string {
  if (!nodeData || nodeData.length === 0) return '[聊天记录]'
  const count = nodeData.length
  const first = nodeData[0]
  let preview = `${first.username}: `
  const firstMsg = first.messages?.[0]
  if (firstMsg) {
    const content = firstMsg.data?.substring(0, 20) || '[消息]'
    preview += content + (firstMsg.data && firstMsg.data.length > 20 ? '...' : '')
  }
  if (count > 1) preview += ` 等${count}条消息`
  return preview
}

export function ChatMessageItem({
  message,
  onResend,
  onButtonClick,
  onImageClick,
  onCopy,
  onNodeClick,
}: ChatMessageItemProps) {
  const [shown, setShown] = useState(false)
  const ref = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            setShown(true)
            observer.disconnect()
          }
        }
      },
      { threshold: 0.1 },
    )
    if (ref.current) observer.observe(ref.current)
    return () => observer.disconnect()
  }, [])

  if (message.type === 'system') {
    return (
      <div className="fd-system-message">
        {message.text}
      </div>
    )
  }

  if (message.type === 'node') {
    return (
      <div ref={ref} className={`fd-message-item fd-message-node ${shown ? 'shown' : ''}`}>
        <img src={message.sender?.avatar} alt="avatar" className="fd-msg-avatar" />
        <div className="fd-msg-content">
          <div className="fd-sender-name">{message.sender?.nickname}</div>
          <div
            className="fd-msg-bubble fd-node-message-bubble"
            onClick={() => message.nodeData && onNodeClick(message.nodeData)}
            role="button"
            tabIndex={0}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && message.nodeData) onNodeClick(message.nodeData)
            }}
          >
            <div className="fd-node-preview">
              <span className="fd-node-icon">📋</span>
              <span className="fd-node-text">{getNodePreview(message.nodeData || [])}</span>
            </div>
            <div className="fd-node-hint">点击查看详情</div>
          </div>
        </div>
      </div>
    )
  }

  const avatar = message.sender?.avatar || avatarMap[message.sender?.nickname || ''] || ''

  return (
    <div ref={ref} className={`fd-message-item fd-message-${message.type} ${shown ? 'shown' : ''}`}>
      <img src={avatar} alt="avatar" className="fd-msg-avatar" />
      <div className="fd-msg-content">
        <div className="fd-sender-name">{message.sender?.nickname}</div>
        {message.html && (
          <div
            className="fd-msg-bubble"
            onClick={(e) => {
              const target = e.target as HTMLElement
              if (target.tagName === 'IMG' && target.classList.contains('chat-image')) {
                onImageClick((target as HTMLImageElement).src)
              }
            }}
            dangerouslySetInnerHTML={{ __html: message.html }}
          />
        )}
        {message.buttons && message.buttons.length > 0 && (
          <div className="fd-button-container">
            {message.buttons.map((button, idx) => (
              <button
                key={idx}
                type="button"
                className={`fd-chat-button ${button.style === 1 ? 'style-1' : 'style-0'}`}
                onClick={() => onButtonClick(button)}
              >
                {button.text || button.data}
              </button>
            ))}
          </div>
        )}
      </div>
      {message.type === 'sent' && (
        <>
          <button
            type="button"
            className="fd-copy-button"
            onClick={() => onCopy({ text: message.text, html: message.html })}
            title="复制到输入框"
          >
            📋
          </button>
          <button
            type="button"
            className="fd-resend-button"
            onClick={() => onResend(message.text || message.html || '')}
            title="重新发送"
          >
            +1
          </button>
        </>
      )}
    </div>
  )
}

// docs/.vitepress/theme/components/chat/ChatMessageItem.vue
<script setup lang="ts">
import type { Message, NodeContent } from './ChatMessageList.vue'

const props = defineProps<{
  message: Message
}>()

const emit = defineEmits<{
  (e: 'resend', text: string): void
  (e: 'buttonClick', button: { text: string; data: string; style?: number }): void
  (e: 'imageClick', src: string): void
  (e: 'mediaClick', payload: { src: string; type: string; element: HTMLElement }): void
  (e: 'copy', payload: { text?: string; html?: string }): void
  (e: 'nodeClick', nodeData: NodeContent[]): void
}>()

function handleClick(event: MouseEvent) {
  const target = event.target as HTMLElement

  // 处理图片点击
  if (target.tagName === 'IMG' && target.classList.contains('chat-image')) {
    emit('imageClick', (target as HTMLImageElement).src)
    return
  }

  // 处理媒体项点击（放大显示）
  if (target.classList.contains('chat-media-item')) {
    const src = target.getAttribute('src') || ''
    const type = target.getAttribute('data-type') || 'image'

    // 触发媒体点击事件，由父组件处理 lightbox 显示
    emit('mediaClick', { src, type, element: target })
  }
}

// 生成 node 消息的预览文本
function getNodePreview(nodeData: NodeContent[]): string {
  if (!nodeData || nodeData.length === 0)
    return '[聊天记录]'
  const count = nodeData.length
  const first = nodeData[0]
  let preview = `${first.username}: `
  const firstMsg = first.messages?.[0]
  if (firstMsg) {
    const content = firstMsg.data?.substring(0, 20) || '[消息]'
    preview += content + (firstMsg.data && firstMsg.data.length > 20 ? '...' : '')
  }
  if (count > 1)
    preview += ` 等${count}条消息`

  return preview
}

// 点击打开合并转发面板
function handleNodeClick() {
  if (props.message.type === 'node' && props.message.nodeData)
    emit('nodeClick', props.message.nodeData)
}
</script>

<template>
  <div class="message-item" :class="`message-${message.type}`">
    <template v-if="message.type === 'system'">
      <div class="system-message">
        {{ message.text }}
      </div>
    </template>
    <template v-else-if="message.type === 'node'">
      <img :src="message.sender?.avatar" alt="avatar" class="avatar">
      <div class="message-content">
        <div class="sender-name">
          {{ message.sender?.nickname }}
        </div>
        <div
          class="message-bubble node-message-bubble"
          @click="handleNodeClick"
        >
          <div class="node-preview">
            <span class="node-icon">📋</span>
            <span class="node-text">{{ getNodePreview(message.nodeData || []) }}</span>
          </div>
          <div class="node-hint">
            点击查看详情
          </div>
        </div>
      </div>
    </template>
    <template v-else>
      <img :src="message.sender?.avatar" alt="avatar" class="avatar">
      <div class="message-content">
        <div class="sender-name">
          {{ message.sender?.nickname }}
        </div>
        <div v-if="message.html" class="message-bubble" @click="handleClick" v-html="message.html" />
        <div v-if="message.buttons && message.buttons.length" class="button-container">
          <button
            v-for="(button, btnIndex) in message.buttons"
            :key="btnIndex"
            class="chat-button"
            :class="{
              'style-0': button.style === 0,
              'style-1': button.style === 1,
            }"
            @click="$emit('buttonClick', button)"
          >
            {{ button.text || button.data }}
          </button>
        </div>
      </div>
      <button v-if="message.type === 'sent'" class="copy-button" @click="$emit('copy', { text: message.text, html: message.html })">
        📋
      </button>
      <button v-if="message.type === 'sent'" class="resend-button" @click="$emit('resend', message.text || message.html || '')">
        +1
      </button>
    </template>
  </div>
</template>

<style scoped>
.message-item {
  display: flex;
  margin-bottom: 1rem;
  max-width: 80%;
}

.message-item.message-system {
  max-width: 100% !important;
}

.message-item.message-node {
  max-width: 70%;
}

.system-message {
  width: 100%;
  text-align: center;
  font-size: 0.8rem;
  color: var(--vp-c-text-3);
  margin-bottom: 0.5rem;
}

.avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  margin-right: 12px;
  flex-shrink: 0;
}

.message-content {
  display: flex;
  flex-direction: column;
}

.sender-name {
  font-size: 0.8em;
  color: var(--vp-c-text-2);
  margin-bottom: 4px;
}

.message-bubble {
  padding: 0.6rem 1rem;
  border-radius: 12px;
  background-color: var(--vp-c-bg-mute);
  word-wrap: break-word;
  overflow-wrap: break-word;
}

/* 合并转发消息样式 */
.node-message-bubble {
  cursor: pointer;
  transition: background-color 0.2s;
}

.node-message-bubble:hover {
  background-color: var(--vp-c-bg-soft);
}

.node-preview {
  display: flex;
  align-items: center;
  gap: 8px;
}

.node-icon {
  font-size: 1.2em;
}

.node-text {
  color: var(--vp-c-text-1);
  font-size: 0.9em;
}

.node-hint {
  font-size: 0.7em;
  color: var(--vp-c-text-3);
  margin-top: 4px;
}

.message-bubble :deep(img.chat-image) {
  max-width: 200px;
  border-radius: 8px;
  display: block;
  cursor: pointer;
  transition: opacity 0.2s;
}

.message-bubble :deep(img.chat-image:hover) {
  opacity: 0.8;
}

.message-sent {
  margin-left: auto;
  flex-direction: row-reverse;
  display: flex;
  align-items: flex-end;
  gap: 8px;
}

.message-sent .avatar {
  margin-right: 0;
  margin-left: 0;
}

.message-sent .message-content {
  align-items: flex-end;
  margin-right: 0;
}

.message-sent .sender-name {
  text-align: right;
}

.message-sent .message-bubble {
  background-color: var(--vp-c-brand);
  color: white;
  margin-right: 0;
}

.resend-button {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  background-color: transparent;
  color: rgb(48, 179, 255);
  border: 1px solid rgb(48, 179, 255);
  font-weight: bold;
  font-size: 0.8rem;
  margin-right: 8px;
  cursor: pointer;
  transition: background-color 0.2s, color 0.2s;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.resend-button:hover {
  background-color: var(--vp-c-brand-soft);
}

.message-sent .resend-button:hover {
  background-color: rgba(255, 255, 255, 0.3);
}

.copy-button {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  background-color: transparent;
  color: rgb(48, 179, 255);
  border: 1px solid rgb(48, 179, 255);
  font-size: 0.8rem;
  margin-right: 4px;
  cursor: pointer;
  transition: background-color 0.2s, color 0.2s;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  padding: 0;
}

.copy-button:hover {
  background-color: var(--vp-c-brand-soft);
}

.message-sent .copy-button:hover {
  background-color: rgba(255, 255, 255, 0.3);
}

/* Button styles */
.button-container {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 8px;
  max-width: 100%;
}

.chat-button {
  padding: 6px 12px;
  border-radius: 6px;
  background-color: transparent;
  cursor: pointer;
  font-size: 0.9em;
  font-weight: 500;
  transition: background-color 0.2s, color 0.2s, border-color 0.2s;
  border: 1px solid;
  min-width: 40px;
  display: inline-flex;
  justify-content: center;
}

/* Style 0: 灰色线框 */
.chat-button.style-0 {
  border-color: var(--vp-c-divider);
  color: var(--vp-c-text-2);
}

.chat-button.style-0:hover {
  background-color: var(--vp-c-bg-mute);
  border-color: var(--vp-c-text-2);
}

/* Style 1: 蓝色线框 */
.chat-button.style-1 {
  border-color: var(--vp-c-brand);
  color: var(--vp-c-brand);
}

.chat-button.style-1:hover {
  background-color: var(--vp-c-brand-soft);
}

/* 在发送者气泡中的按钮样式调整 */
.message-sent .chat-button.style-0 {
  border-color: rgba(255, 255, 255, 0.5);
  color: rgba(255, 255, 255, 0.9);
}

.message-sent .chat-button.style-0:hover {
  background-color: rgba(255, 255, 255, 0.15);
  border-color: white;
}

.message-sent .chat-button.style-1 {
  border-color: white;
  color: white;
  background-color: rgba(255, 255, 255, 0.2);
}

.message-sent .chat-button.style-1:hover {
  background-color: rgba(255, 255, 255, 0.3);
}
</style>
